---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:8.0.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: test-node-16
  image: node:16-alpine
  commands: ["npm run test:ci -s"]

- name: test-node-18
  image: node:18-alpine
  commands: ["npm run test:ci -s"]

- name: test-node-20
  image: node:20-alpine
  commands: ["npm run test:ci -s"]

- name: release
  image: livingdocs/semantic-release:v2.1.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: f1328ec1c3d6487efebe7903be6567faf54f4158ae99333919a61b602b227a58

...
